import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialWorkingSchema2026092701000 implements MigrationInterface {
    name = 'InitialWorkingSchema2026092701000'

    public async up(queryRunner: QueryRunner): Promise<void> {
        const expectedTables = [
            'addons', 'users', 'catering_orders', 'catering_packages',
            'catering_quotes', 'change_requests', 'coupons', 'leads',
            'menu_items', 'categories', 'messages', 'notification_logs',
            'orders', 'settings',
        ];
        const existingRows: Array<{ table_name: string }> = await queryRunner.query(
            `SELECT table_name FROM information_schema.tables WHERE table_schema = current_schema() AND table_type = 'BASE TABLE' AND table_name <> 'typeorm_migrations'`,
        );
        const existing = existingRows.map(row => row.table_name).sort();
        if (existing.length > 0) {
            if (JSON.stringify(existing) !== JSON.stringify([...expectedTables].sort())) {
                throw new Error('Existing database schema is not the expected working schema; baseline refused.');
            }
            const allowedDefaults = new Set([
                'catering_orders.selections', 'catering_packages.categories',
                'menu_items.choices', 'settings.businessHours',
                'settings.homepageDraft', 'settings.homepagePublished',
            ]);
            const differences = await queryRunner.connection.driver.createSchemaBuilder().log();
            const unexpected = differences.upQueries.filter(({ query }) => {
                const match = /^ALTER TABLE "([^"]+)" ALTER COLUMN "([^"]+)" SET DEFAULT /.exec(query);
                return !match || !allowedDefaults.has(`${match[1]}.${match[2]}`);
            });
            if (unexpected.length > 0) {
                throw new Error('Existing database differs beyond safe JSONB defaults; baseline refused.');
            }
            return;
        }
        await queryRunner.query(`CREATE TABLE "addons" ("_id" character varying(128) NOT NULL, "name" character varying NOT NULL, "nameTranslations" jsonb, "description" character varying NOT NULL DEFAULT '', "descriptionTranslations" jsonb, "price" double precision NOT NULL, "pricingType" character varying(16) NOT NULL DEFAULT 'fixed', "category" character varying(24) NOT NULL DEFAULT 'other', "isActive" boolean NOT NULL DEFAULT true, "sortOrder" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_f0b02b64aca8a82f0f350dd9d40" PRIMARY KEY ("_id"))`);
        await queryRunner.query(`CREATE TABLE "users" ("_id" character varying(128) NOT NULL, "username" character varying NOT NULL, "name" character varying NOT NULL DEFAULT '', "phone" character varying NOT NULL, "address" character varying, "eventPreferences" jsonb, "email" character varying NOT NULL, "password" character varying NOT NULL, "role" character varying(24) NOT NULL DEFAULT 'user', "resetPasswordToken" character varying, "resetPasswordExpires" TIMESTAMP WITH TIME ZONE, "isVerified" boolean NOT NULL DEFAULT false, "verificationPin" character varying, "verificationPinExpires" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_46c438e5a956fb9c3e86e73e321" PRIMARY KEY ("_id"))`);
        await queryRunner.query(`CREATE TABLE "catering_orders" ("_id" character varying(128) NOT NULL, "userId" character varying, "packageId" character varying NOT NULL, "packageName" character varying NOT NULL, "selections" jsonb NOT NULL DEFAULT '[]'::jsonb, "guests" integer NOT NULL, "eventDate" TIMESTAMP WITH TIME ZONE NOT NULL, "eventLocation" character varying, "pricePerPerson" double precision NOT NULL, "totalPrice" double precision NOT NULL, "customerInfo" jsonb NOT NULL, "status" character varying(24) NOT NULL DEFAULT 'pending', "paymentStatus" character varying(24) NOT NULL DEFAULT 'unpaid', "stripeSessionId" character varying, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_8f41d454c8733c4c0221ba70253" PRIMARY KEY ("_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3c0aea2e00d34380f97af0f596" ON "catering_orders"  ("userId") `);
        await queryRunner.query(`CREATE TABLE "catering_packages" ("_id" character varying(128) NOT NULL, "name" character varying NOT NULL, "nameTranslations" jsonb, "description" character varying, "descriptionTranslations" jsonb, "basePrice" double precision NOT NULL, "minGuests" integer NOT NULL, "maxGuests" integer, "categories" jsonb NOT NULL DEFAULT '[]'::jsonb, "image" character varying, "available" boolean NOT NULL DEFAULT true, "isActive" boolean NOT NULL DEFAULT true, "sortOrder" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_1d0b5776050fd73069334cf2d52" PRIMARY KEY ("_id"))`);
        await queryRunner.query(`CREATE TABLE "catering_quotes" ("_id" character varying(128) NOT NULL, "name" character varying NOT NULL, "email" character varying NOT NULL, "phone" character varying NOT NULL, "eventDate" TIMESTAMP WITH TIME ZONE NOT NULL, "guests" integer NOT NULL, "location" character varying NOT NULL, "budgetRange" character varying, "eventType" character varying, "notes" character varying, "utmSource" character varying, "campaign" character varying, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_d52c84aaa8f84cb2cf10003c4fe" PRIMARY KEY ("_id"))`);
        await queryRunner.query(`CREATE TABLE "change_requests" ("_id" character varying(128) NOT NULL, "userId" character varying NOT NULL, "orderId" character varying NOT NULL, "requestedChanges" character varying NOT NULL, "status" character varying(16) NOT NULL DEFAULT 'pending', "adminNotes" character varying, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_389abb58dc6dd43a65d9b2953c4" PRIMARY KEY ("_id"))`);
        await queryRunner.query(`CREATE TABLE "coupons" ("_id" character varying(128) NOT NULL, "code" character varying NOT NULL, "discountType" character varying(16) NOT NULL DEFAULT 'percentage', "discountValue" double precision NOT NULL, "minOrderAmount" double precision NOT NULL DEFAULT '0', "maxUses" integer NOT NULL DEFAULT '0', "usedCount" integer NOT NULL DEFAULT '0', "validFrom" TIMESTAMP WITH TIME ZONE, "validUntil" TIMESTAMP WITH TIME ZONE, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_e025109230e82925843f2a14c48" UNIQUE ("code"), CONSTRAINT "PK_4d1f01ad8c320e102c55473bc17" PRIMARY KEY ("_id"))`);
        await queryRunner.query(`CREATE TABLE "leads" ("_id" character varying(128) NOT NULL, "name" character varying NOT NULL, "email" character varying NOT NULL, "phone" character varying NOT NULL, "eventDate" character varying, "guests" integer, "location" character varying, "message" character varying, "package" character varying, "utmSource" character varying, "campaign" character varying, "status" character varying(24) NOT NULL DEFAULT 'OPEN', "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_0d1eaebfcc1b777a14d74f8472e" PRIMARY KEY ("_id"))`);
        await queryRunner.query(`CREATE TABLE "menu_items" ("_id" character varying(128) NOT NULL, "name" character varying(200) NOT NULL, "NameTranslations" jsonb, "description" text, "DescriptionTranslations" jsonb, "price" double precision NOT NULL, "image" character varying(500), "categoryId" character varying(128) NOT NULL, "spiceLevel" integer NOT NULL DEFAULT '0', "available" boolean NOT NULL DEFAULT true, "isVeg" boolean NOT NULL DEFAULT false, "stockCount" integer NOT NULL DEFAULT '0', "dailyAvailability" boolean NOT NULL DEFAULT true, "isActive" boolean NOT NULL DEFAULT true, "choices" jsonb NOT NULL DEFAULT '[]'::jsonb, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_b9dfd50252b29b2552d4f703a32" PRIMARY KEY ("_id"))`);
        await queryRunner.query(`CREATE TABLE "categories" ("_id" character varying(128) NOT NULL, "name" character varying(200) NOT NULL, "nameTranslations" jsonb, "type" character varying(24) NOT NULL DEFAULT 'Veg', "order" integer NOT NULL DEFAULT '0', "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_41b10fde49e2e6b0c771fa2ad5e" PRIMARY KEY ("_id"))`);
        await queryRunner.query(`CREATE TABLE "messages" ("_id" character varying(128) NOT NULL, "name" character varying NOT NULL, "email" character varying NOT NULL, "phone" character varying NOT NULL, "message" text NOT NULL, "read" boolean NOT NULL DEFAULT false, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_79fc28532440f34f2d1e725940d" PRIMARY KEY ("_id"))`);
        await queryRunner.query(`CREATE TABLE "notification_logs" ("_id" character varying(128) NOT NULL, "eventId" character varying NOT NULL, "userId" character varying, "referenceId" character varying, "type" character varying(16) NOT NULL, "status" character varying(16) NOT NULL DEFAULT 'pending', "errorMessage" character varying, "payload" jsonb, "isCleared" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_d314a54dcd24fe36a97b8f2efc0" UNIQUE ("eventId", "type"), CONSTRAINT "PK_7e6c9e83e55d8dcfcdcf97b007b" PRIMARY KEY ("_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d348e06bb339e4439d60b1480d" ON "notification_logs"  ("userId") `);
        await queryRunner.query(`CREATE TABLE "orders" ("_id" character varying(128) NOT NULL, "userId" character varying, "items" jsonb NOT NULL, "total" double precision NOT NULL, "status" character varying(24) NOT NULL DEFAULT 'pending', "pickupTime" TIMESTAMP WITH TIME ZONE NOT NULL, "customerInfo" jsonb NOT NULL, "paymentStatus" character varying(24) NOT NULL DEFAULT 'unpaid', "stripeSessionId" character varying, "utmSource" character varying, "couponCode" character varying, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_252c2a9858ce5be707f5c84e78a" PRIMARY KEY ("_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_151b79a83ba240b0cb31b2302d" ON "orders"  ("userId") `);
        await queryRunner.query(`CREATE TABLE "settings" ("_id" character varying(128) NOT NULL, "siteName" character varying NOT NULL DEFAULT 'Tamil Food Thaya', "address" character varying NOT NULL DEFAULT '', "phone" character varying NOT NULL DEFAULT '', "email" character varying NOT NULL DEFAULT '', "whatsapp" character varying NOT NULL DEFAULT '', "businessHours" jsonb NOT NULL DEFAULT '{"monday":"Gesloten","tuesday":"12:00 - 22:00","wednesday":"12:00 - 22:00","thursday":"12:00 - 22:00","friday":"12:00 - 23:00","saturday":"12:00 - 23:00","sunday":"12:00 - 22:00"}'::jsonb, "facebookUrl" character varying NOT NULL DEFAULT '', "instagramUrl" character varying NOT NULL DEFAULT '', "ordersEnabled" boolean NOT NULL DEFAULT true, "homepageDraft" jsonb DEFAULT '{}'::jsonb, "homepagePublished" jsonb DEFAULT '{}'::jsonb, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_cefed4452b0b1f9d289c1cc1340" PRIMARY KEY ("_id"))`);
        await queryRunner.query(`ALTER TABLE "menu_items" ADD CONSTRAINT "FK_d56e5ccc298e8bf721f75a7eb96" FOREIGN KEY ("categoryId") REFERENCES "categories"("_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        void queryRunner;
        throw new Error('Initial schema migration cannot be reverted automatically; restore a verified backup instead.');
    }

}
